In [ ]:
# Mathematical functions

# Trigonometric functions
import numpy as np
import cmath
x=np.array([1,8,3,9])
print(x)
print(np.sin(x))
print(np.cos(x))
print(np.cos(x))

y=np.array([0.1,0.2,0.6,0.7])
print(y)
print(np.arccos(y))
print(np.arcsin(y))
print(np.arctan(y))

[1 8 3 9]
[0.84147098 0.98935825 0.14112001 0.41211849]
[ 0.54030231 -0.14550003 -0.9899925  -0.91113026]
[ 0.54030231 -0.14550003 -0.9899925  -0.91113026]
[0.1 0.2 0.6 0.7]
[1.47062891 1.36943841 0.92729522 0.79539883]
[0.10016742 0.20135792 0.64350111 0.7753975 ]
[0.09966865 0.19739556 0.5404195  0.61072596]


In [ ]:
#Hyperbolic functions

print(np.sinh(y))
print(np.cosh(y))
print(np.tanh(y))

[0.10016675 0.201336   0.63665358 0.7585837 ]
[1.00500417 1.02006676 1.18546522 1.25516901]
[0.09966799 0.19737532 0.53704957 0.60436778]


In [ ]:
#Rounding
z=np.array([2.77,1.49,1.59,8.27])
print(z)
print(np.around(z))
print(np.round(z))
print(np.rint(z))
print(np.fix(z))

[2.77 1.49 1.59 8.27]
[3. 1. 2. 8.]
[3. 1. 2. 8.]
[3. 1. 2. 8.]
[2. 1. 1. 8.]


In [ ]:
# Sums, products, differences
u=np.array([1,2,3,4])
print(np.prod(u))
print(np.sum(u))
print(np.nanprod(u))
print(np.nansum(u))
print(np.cumprod(u))
print(np.cumsum(u))

24
10
24
10
[ 1  2  6 24]
[ 1  3  6 10]


In [ ]:
# Exponents and logarithms
print(np.exp(u))
print(np.expm1(u))
print(np.exp2(u))
print(np.log(u))
print(np.log10(u))
print(np.log2(u))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1.71828183  6.3890561  19.08553692 53.59815003]
[ 2.  4.  8. 16.]
[0.         0.69314718 1.09861229 1.38629436]
[0.         0.30103    0.47712125 0.60205999]
[0.        1.        1.5849625 2.       ]


In [ ]:
# Other special functions
print(np.i0(u))
print(np.sinc(u))

[ 1  2  4 11]
[ 3.89817183e-17 -3.89817183e-17  3.89817183e-17 -3.89817183e-17]


In [ ]:
# Floating point routines
v=np.array([-0.5,2,0.64,-5])
print(v)
print(np.signbit(v))
print(np.copysign(v[0],v[1]))
print(np.frexp(v[3]))


[-0.5   2.    0.64 -5.  ]
[ True False False  True]
0.5
(-0.625, 3)


In [ ]:
# Rational routines
w=np.array([5,18])
print(w)
print(np.lcm(w[0],w[1]))
print(np.gcd(w[0],w[1]))

[ 5 18]
90
1


In [ ]:
# Arithmetic operations
print(np.add(w[0],w[1]))
print(np.reciprocal(w))
print(np.positive(w))
print(np.negative(w))
print(np.multiply(w[0],w[1]))
print(np.divide(w[0],w[1]))
print(np.power(w[0],w[1]))
print(np.subtract(w[0],w[1]))

23
[0 0]
[ 5 18]
[ -5 -18]
90
0.2777777777777778
3814697265625
-13


In [ ]:
# Handling complex numbers
s=complex(3,-4)
print(np.real(s))
print(np.imag(s))
print(np.angle(s))


3.0
-4.0
-0.9272952180016122


In [ ]:
# Miscellaneous
print(np.convolve(2,w[0:2]))
print(np.clip(2,w[0],w[1]))
print(np.sqrt(w))
print(np.cbrt(w))
print(np.square(w))
print(np.absolute(w))
print(np.maximum(w[0],w[1]))

[10 36]
5
[2.23606798 4.24264069]
[1.70997595 2.62074139]
[ 25 324]
[ 5 18]
18


In [ ]:
# Stacking
# Vertical Stack
# Depth Stack

xx=np.arange(9).reshape(3,3)
print(xx)
yy=np.arange(5,14).reshape(3,3)
print(yy)
zz=np.vstack((xx,yy))  # Vertical Stack
print(zz)
ss=np.dstack((xx,yy))  # Depth stack
print(ss)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[[ 0  5]
  [ 1  6]
  [ 2  7]]

 [[ 3  8]
  [ 4  9]
  [ 5 10]]

 [[ 6 11]
  [ 7 12]
  [ 8 13]]]
